### PR TITLE
Fixed an error where xcopy fails due to a space in $(SolutionDir)

### PR DESCRIPTION
**Pull request by jannisj1**

### CODE REVIEW

**Comment by Jacob-Mango** [comment]
This explains that error I had. I wonder why it didn't appear in the video? I just copied the files myself.

**Comment by jannisj1** [comment]
> This explains that error I had. I wonder why it didn't appear in the video? I just copied the files myself.
His path to sparky has no spaces I guess

**Comment by jannisj1** [comment]
> I wonder why it didn't appear in the video?

He has no spaces in his sparky path I guess. The problem is that as soon as you have a space in your path and you pass it without quotation marks xcopy will receive multiple args instead of the one path, because space is obviously the standard argument-seperator. The quotation marks tell the commandline-engine (or whatever it is called) to pass everything between them as one arg and not seperate it.

**Comment by TheCherno** [comment]
Yes, you are correct. If you have no spaces in the `$(SolutionDir)` path, then this doesn't result in an error. Thanks for your pull request; merging.

**Pull request merged**
