### PR TITLE
Implemented Better Logging In The Win32Log.cpp

### PR DESCRIPTION
**Pull request by ghost**
I added some override methods for the sparky platform log. Added a log to file method to it as well.

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Sparky-core/src/sp/platform/windows/Win32Log.cpp - line 65 a space or other seperator should be added after filename.

**Comment by ghost** [comment]
i don't think it's a good idea to use C headers

**Comment by jannisj1** [comment]
> i don't think it's a good idea to use C headers

Give reasoning please. Otherwise it's no constructive criticism.

**Comment by ghost** [comment]
I heard that its rather bad to use them because they are kind of deprecated and so on. And it is always better to write modern c++11 code i guess :P 
My comment wasnt meant as critic and that its bad practice it was more of a tip. Please correct me if i am wrong but i dont want to start a discussion about that stuff on here ^^

**Comment by jannisj1** [comment]
@unpause didn't want to start a discussion too, but I think it's better to just give your reasoning with an opinion rather than waiting for somebody to ask for it :)
But back to the point: There is nothing wrong with including c-headers, in fact the c++ standard library includes the c headers at some point anyways (atleast in msvc++). Using the actual c functions _**alot**_ is debatable thats true.

**Pull request closed without merging**
