### PR TITLE
Added Checkboxes and a small effect on buttons and checkboxes 

### PR DESCRIPTION
**Pull request by ghost**
- Only been working for the past hour, so there may be things to change (hope you like the small effect ;) ).
  - Also I've not tested the interaction with the rest of the engine, it's just a graphical addition.
- @TheCherno Do you see some more features that could be added ?

(btw, it's my first ever commit to Sparky so I hope I've done well)

### CODE REVIEW

**Comment by ghost** [comment]
I forgot to say that I'm working on a TextBox, but I've just did some design on paper, no code at all.

(I can't see why CI isn't working, never been working with it could you explain me what it does ?)

**Comment by BRGCodeCampus** [comment]
I've been working on TextFields all the day, but I can't figure out why KeyEvents aren't working. Do they work in other situations ? I've implemeted TextFields with a messy thing to get any key pressed with `Input::IsKeypressed()`

**Comment by TheCherno** [comment]
I'm still in the middle of integrating CI (Continuous Integration), so it may be falsely erroring you. Basically CI just does a build of the solution every time new code is pushed (including pull requests), to verify that there are no compile errors / any other checks that need to run.

Anyways, I'm not sure why the Debug build failed, but if you take a look at the [Release log](https://ci.appveyor.com/project/TheCherno/sparky/build/job/cf2y6d8yy5bijqwl) you'll be able to see the errors.

**Comment by ghost** [comment]
Yup, saw it and going to correct it asap 
Thanks for reply

**Comment by ghost** [comment]
I've managed to correct the error (stupid one) but I cannot understand why there's a linking error at the end !

**Pull request closed without merging**
