### PR TITLE
Fix mat4::Rotate bug

### PR DESCRIPTION
**Pull request by Crisspl**
https://github.com/TheCherno/Sparky/issues/125

### CODE REVIEW

**Comment by blroot** [comment]
This is actually true, could cause some undesirable effects

**Comment by Crisspl** [comment]
But still waiting for merge :/ @TheCherno what do you think about it?

**Comment by Crisspl** [comment]
Oh, ok, already fixed.

**Comment by TheCherno** [comment]
Hey, thanks for this. Please remove the all the extra files in your commit (we just need mat4.cpp), and I'll merge.

**Comment by Crisspl** [comment]
Ok, done. I'm quite new to git and somehow the commit got two "owners", but anyway - I think it's ok now.

**Pull request merged**
